// This class is automatically included in FastlaneRunner during build

// This autogenerated file will be overwritten or replaced during build time, or when you initialize `gym`
//
//  ** NOTE **
//  This file is provided by fastlane and WILL be overwritten in future updates
//  If you want to add extra functionality to this project, create a new file in a
//  new group so that it won't be marked for upgrade
//

class Gymfile: GymfileProtocol {
	var scheme: String? = "Monolingual"

	var outputDirectory = "./build"

	var exportOptions: [String : Any]? = [
		"compileBitcode": false,
		"embedOnDemandResourcesAssetPacksInBundle": true,
		"iCloudContainerEnvironment": "Production",
		"method": "developer-id",
		"thinning": "none",
		"uploadBitcode": false,
		"uploadSymbols": true
	]
}

// Generated with fastlane 2.77.0
