---
version: "2"
checks:
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
  swiftlint:
    enabled: true
exclude_patterns:
  - "SMJobBlessUtil.py"
  - "fastlane/"
  - "Pods/"
