language: objective-c
xcode_workspace: Monolingual.xcworkspace
xcode_scheme: Travis
osx_image: xcode10.2
cache:
- bundler
install:
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
before_script:
- "./scripts/add-key.sh"
#- "./scripts/install-swift.sh"
script:
- bundle exec fastlane test
after_script:
- "./scripts/remove-key.sh"
env:
  global:
    - secure: "EGO9AUBftc8IOUYlFG1R2efs04eDWNFlikkuIt3UfY/zntHZD6FqSqbI3zHGiWZFSh5WH8xj9yYVa+dj9C8IAnnJZQ2is9IpBISayBdmoaAXhDedm3UpfCbnPUkYOgvKHd4sFJFYf+BrizTDcpKo1oeEXfYcqfMKXWwt4jBJrbY="
