language: objective-c
xcode_workspace: Monolingual.xcworkspace
xcode_scheme: Travis
osx_image: xcode7
cache:
- bundler
- cocoapods
before_script:
- "./scripts/add-key.sh"
- brew update && brew upgrade xctool || true
after_script:
- "./scripts/remove-key.sh"
env:
  global:
    secure: I8qZoxRt+YPMqfVk19YrOuiuUg0Vtzr1NN3FSk9sqpckFUy1Hw63L3Ajntj28WiwjYgj7AgnMNPk4ZFRn4j23cPUuMvUApEFZk+prsXt5y46cxrmUqeKNfSU57aA4xEkXFOZ+I268veuM4ziRr9NnJ+XiBDlFMmzS1kOBQN5szU=
