# Site settings
title: Monolingual
tagline: "Removing unnecessary language resources from macOS"
#email: your-email@domain.com
description: "Monolingual is a program for removing unnecessary language resources from macOS in order to reclaim several hundred megabytes of disk space."
baseurl: "/Monolingual/"
url: "https://ingmarstein.github.io"
lang: en
twitter_username: MonolingualMac
github_username:  IngmarStein

# Build settings
markdown: kramdown
permalink: pretty

# Data settings
github_url: https://github.com/IngmarStein/Monolingual
github_version_url: https://github.com/IngmarStein/Monolingual/releases/tag/v
github_download_url: https://github.com/IngmarStein/Monolingual/releases/download/vVERSION/Monolingual-VERSION

defaults:
  -
    scope:
      path: ''
      type: data
    values:
      history: no
  -
    scope:
      path: ''
      type: "pages"
    values:
      layout: 'default'
