# Site settings
title: Monolingual
#email: your-email@domain.com
description: "Monolingual"
baseurl: ""
#url: "http://yourdomain.com"
twitter_username: IngmarStein
github_username:  IngmarStein

# Build settings
markdown: kramdown
permalink: pretty
