pool:
  vmImage: 'macOS 10.14'
variables:
  DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
steps:
- script: bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  displayName: 'Install gems'
- script: brew bundle
  displayName: 'Install homebrew dependencies'
- script: "./scripts/add-key.sh"
  displayName: 'Add key'
  env:
    KEY_PASSWORD: $(secret.keyPassword)
- script: xcodebuild -resolvePackageDependencies
  displayName: Resolve Swift Package Manager dependencies (https://github.com/fastlane/fastlane/pull/15505)
- script: bundle exec fastlane test
  displayName: 'Build and test with fastlane'
- script: "./scripts/remove-key.sh"
  displayName: 'Remove key'
